CREATE TABLE CAR_BRAND (
     CAR_BRAND_ID BIGINT  NOT NULL AUTO_INCREMENT,
     CAR_BRAND_NAME VARCHAR(45),
     PRIMARY KEY (CAR_BRAND_ID)
);

CREATE TABLE  CAR_MODEL (
     CAR_MODEL_ID BIGINT  NOT NULL AUTO_INCREMENT,
     CAR_MODEL_NAME VARCHAR(50),
     CAR_BRAND_ID BIGINT,
     PRIMARY KEY (CAR_MODEL_ID),
     FOREIGN KEY (CAR_BRAND_ID) REFERENCES CAR_BRAND(CAR_BRAND_ID)
);

CREATE TABLE TYPE_FINES(
     TYPE_FINES_ID BIGINT  NOT NULL AUTO_INCREMENT,
     TYPE_FINES_NAME VARCHAR(80),
     AMOUNT_DUTY INT,
     PRIMARY KEY (TYPE_FINES_ID)
);

CREATE TABLE OWNERS (
     OWNER_ID BIGINT  NOT NULL AUTO_INCREMENT,
     OWNER_NAME VARCHAR(80),
     PRIMARY KEY(OWNER_ID)
);

CREATE TABLE LICENSE_PLATE_NUMBER (
     LICENSE_PLATE_NUMBER_ID BIGINT  NOT NULL AUTO_INCREMENT,
     CAR_MODEL_ID BIGINT,
     OWNER_ID BIGINT,
     LICENSE_PLATE_NUMBER_NAME VARCHAR(9),
     PRIMARY KEY (LICENSE_PLATE_NUMBER_ID),
     FOREIGN KEY (OWNER_ID) REFERENCES OWNERS(OWNER_ID),
     FOREIGN KEY (CAR_MODEL_ID) REFERENCES CAR_MODEL(CAR_MODEL_ID)
);

CREATE TABLE FINES_INFORMATION (
     FINES_INFORMATION_ID BIGINT  NOT NULL AUTO_INCREMENT,
     LICENSE_PLATE_NUMBER_ID BIGINT,
     TYPE_FINES_ID BIGINT,
     PRIMARY KEY (FINES_INFORMATION_ID),
     FOREIGN KEY (TYPE_FINES_ID) REFERENCES TYPE_FINES (TYPE_FINES_ID),
     FOREIGN KEY (LICENSE_PLATE_NUMBER_ID) REFERENCES LICENSE_PLATE_NUMBER (LICENSE_PLATE_NUMBER_ID)
);
