INSERT INTO CAR_BRAND (CAR_BRAND_NAME) VALUES ('brand-1');
INSERT INTO CAR_BRAND (CAR_BRAND_NAME) VALUES ('brand-2');
INSERT INTO CAR_BRAND (CAR_BRAND_NAME) VALUES ('brand-3');

INSERT INTO CAR_MODEL (CAR_MODEL_NAME,CAR_BRAND_ID) VALUES ('domain-1',1);
INSERT INTO CAR_MODEL (CAR_MODEL_NAME,CAR_BRAND_ID) VALUES ('domain-2',2);
INSERT INTO CAR_MODEL (CAR_MODEL_NAME,CAR_BRAND_ID) VALUES ('domain-3',3);

INSERT INTO TYPE_FINES (TYPE_FINES_NAME,AMOUNT_DUTY) VALUES ('тип-1',1500);
INSERT INTO TYPE_FINES (TYPE_FINES_NAME,AMOUNT_DUTY) VALUES ('тип-2',5000);
INSERT INTO TYPE_FINES (TYPE_FINES_NAME,AMOUNT_DUTY) VALUES ('тип-3',20000);
INSERT INTO TYPE_FINES (TYPE_FINES_NAME,AMOUNT_DUTY) VALUES ('тип-4',1250);
INSERT INTO TYPE_FINES (TYPE_FINES_NAME,AMOUNT_DUTY) VALUES ('тип-5',15000);

INSERT INTO OWNERS (OWNER_NAME) VALUES ('Ваня');
INSERT INTO OWNERS (OWNER_NAME) VALUES ('Леха');
INSERT INTO OWNERS (OWNER_NAME) VALUES ('Макс');

INSERT INTO LICENSE_PLATE_NUMBER (CAR_MODEL_ID,OWNER_ID,LICENSE_PLATE_NUMBER_NAME) VALUES (1,1,'А324НЕ222');
INSERT INTO LICENSE_PLATE_NUMBER (CAR_MODEL_ID,OWNER_ID,LICENSE_PLATE_NUMBER_NAME) VALUES (2,2,'И675ТН457');
INSERT INTO LICENSE_PLATE_NUMBER (CAR_MODEL_ID,OWNER_ID,LICENSE_PLATE_NUMBER_NAME) VALUES (3,3,'У784ЛО223');
INSERT INTO LICENSE_PLATE_NUMBER (CAR_MODEL_ID,OWNER_ID,LICENSE_PLATE_NUMBER_NAME) VALUES (3,3,'Х784ЛО227');
INSERT INTO LICENSE_PLATE_NUMBER (CAR_MODEL_ID,OWNER_ID,LICENSE_PLATE_NUMBER_NAME) VALUES (3,3,'Б784ЛО226');

INSERT INTO FINES_INFORMATION (LICENSE_PLATE_NUMBER_ID,TYPE_FINES_ID) VALUES (1,1);
INSERT INTO FINES_INFORMATION (LICENSE_PLATE_NUMBER_ID,TYPE_FINES_ID) VALUES (2,2);
INSERT INTO FINES_INFORMATION (LICENSE_PLATE_NUMBER_ID,TYPE_FINES_ID) VALUES (3,3);
INSERT INTO FINES_INFORMATION (LICENSE_PLATE_NUMBER_ID,TYPE_FINES_ID) VALUES (4,3);
INSERT INTO FINES_INFORMATION (LICENSE_PLATE_NUMBER_ID,TYPE_FINES_ID) VALUES (5,3);

